# Exercises

In this section we have one exercise:
1. Implement the polynomial kernel.

## Polynomial kernel

You need to extend the ``build_kernel`` function and implement the polynomial kernel if the ``kernel_type`` is set to 'poly'. The equation that needs to be implemented:
\begin{equation}
K=(X^{T}*Y)^{d}.
\end{equation}

In [ ]:
import numpy as np

def build_kernel(data_set, kernel_type='linear'):
    kernel = np.dot(data_set, data_set.T)
    if kernel_type == 'rbf':
        sigma = 1.0
        objects_count = len(data_set)
        b = np.ones((len(data_set), 1))
        kernel -= 0.5 * (np.dot((np.diag(kernel)*np.ones((1, objects_count))).T, b.T)
                         + np.dot(b, (np.diag(kernel) * np.ones((1, objects_count))).T.T))
        kernel = np.exp(kernel / (2. * sigma ** 2))
    elif kernel_type == 'poly':
        d = 2  # degree parameter
        kernel = kernel ** d
    return kernel

In [9]:
# Test of polynomial kernel
X = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)

# Linear kernel
kernel_linear = build_kernel(X, kernel_type='linear')
print("Linear kernel:")
print(kernel_linear)
print()

# Polynomial kernel
kernel_poly = build_kernel(X, kernel_type='poly')
print("Polynomial kernel (d=2):")
print(kernel_poly)
print()

# Verification
print("Is polynomial kernel a square of linear kernel?")
print(np.allclose(kernel_poly, kernel_linear ** 2))

Linear kernel:
[[ 5. 11. 17.]
 [11. 25. 39.]
 [17. 39. 61.]]

Polynomial kernel (d=2):
[[  25.  121.  289.]
 [ 121.  625. 1521.]
 [ 289. 1521. 3721.]]

Is polynomial kernel a square of linear kernel?
True
